Origin code branch
avalon-dev-j110/laboratornaya-rabota-no2-DenisFilichev pull request #1
Opened 2020-03-31 11:43 UTC by DenisFilichev

Код готов к проверке.

2020-04-02 06:42 UTC, KolosovKD requested changes
Очень прилично, но нужно несколько доработок.

2020-04-02 06:42 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +        return maxArea;
Если передать в этот метод массив new Shape[0] будет ошибка. Будет не лишним проверить в самом начале, что длина массива больше нуля.

2020-04-02 06:42 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +        }
Хорошее решение с генерацией случайных чисел. Гарантирует ли оно наверняка что в массиве в итоге будут присутствовать хотя бы по одной фигуре  каждого типа? Если есть вероятность что генератор может ни разу не выдать какое-то значение, стоит заполнить первые три ячейки массива явно, чтобы выполнить условие присутствия в массиве всех типов фигур.

2020-04-02 06:42 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Circle.java
> +    PointOfShape secondPoint = new PointOfShape();
Здесь лучше использовать интерфейс.
Point firstPoint firstPoint;
Point secondPoint secondPoint;

2020-04-02 06:42 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Circle.java
> +    }
если у вас поля типа точка, логично сделать конструктор с параметрами типа точка

public Circle (Point firstPoint, Point secondPoint) {
  .........
}

2020-04-02 06:42 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Point.java
>  }
Добавьте в итерфейс еще методы setX() и setY(), чтобы использовать везде где возможно интерфейс.

2020-04-02 06:42 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/PointOfShape.java
> +
Добавьте конструктор с двумя параметрами - так вы гарантируете, что не может быть создано точки только с одной координатой в обход вашего конструктора.

2020-04-02 06:42 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/SegmentBetweenPoints.java
> +public class SegmentBetweenPoints {
Вопрос для дискуссии - Почему это класс, а не интерфейс?

2020-04-02 09:25 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j10/labs/shapes/SegmentBetweenPoints.java
> +public class SegmentBetweenPoints {
Если я правильно понимаю, то в интерфейсе нельзя создать тело метода которое к тому же возвращает при вызове конкретное значение.
В моем случае создан статический метод в отдельном классе для расчета длины отрезка по заданным координатам без создания экземпляра класса.

2020-04-12 17:24 UTC, konivex requested changes
Исправьте замечание.

2020-04-12 17:24 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +        if(shapes==null){return null;}
Замечание Кирилла Дмитриевича не исправлено.

2020-04-12 17:24 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/shapes/Rectangle.java
> +    public Rectangle (Point firstPoint, Point secondPoint, int angle){
Мудрёный прямоугольник. :)

2020-04-13 15:17 UTC, DenisFilichev commented on src/ru/avalon/java/dev/j10/labs/shapes/Rectangle.java
> +    public Rectangle (Point firstPoint, Point secondPoint, int angle){
Прямоугольник строится по двум точкам и углу между диагоналями. Он может быть повернут относительно осей.

2020-04-13 15:19 UTC, closed without merging

2020-04-13 15:20 UTC, konivex commented
Исправьте замечания и повторите pull request.